# Generated by Django 3.0.7 on 2020-09-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
