# Generated by Django 3.0.8 on 2020-09-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student_register',
            table='Students_data',
        ),
    ]
